In [3]:
import numpy as np
y = np.ones(40)*0.5
np.arctanh(np.clip(y, np.tanh(-3), np.tanh(3)))

array([0.54930614, 0.54930614, 0.54930614, 0.54930614, 0.54930614,
       0.54930614, 0.54930614, 0.54930614, 0.54930614, 0.54930614,
       0.54930614, 0.54930614, 0.54930614, 0.54930614, 0.54930614,
       0.54930614, 0.54930614, 0.54930614, 0.54930614, 0.54930614,
       0.54930614, 0.54930614, 0.54930614, 0.54930614, 0.54930614,
       0.54930614, 0.54930614, 0.54930614, 0.54930614, 0.54930614,
       0.54930614, 0.54930614, 0.54930614, 0.54930614, 0.54930614,
       0.54930614, 0.54930614, 0.54930614, 0.54930614, 0.54930614])

In [4]:
np.tanh(-3)

-0.9950547536867305

In [5]:
np.tanh(3)

0.9950547536867305

In [6]:
np.clip(y, np.tanh(-3), np.tanh(3))

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5])

In [7]:
np.arctanh(0.5)

0.5493061443340549

In [8]:
np.log([1,2,3])

array([0.        , 0.69314718, 1.09861229])

In [ ]:
import numpy as np

dlatent_array = dlatent_data.reshape((-1, 18*512))
dlatent_array_cut = np.copy(dlatent_array)
dlatent_array_cut = dlatent_array_cut[:, 0:8*512]


feature_gender = np.array([x['faceAttributes']['gender'] == 'male' for x in labels_data])
feature_age = np.array([x['faceAttributes']['age'] for x in labels_data])
feature_smile = np.array([x['faceAttributes']['smile'] for x in labels_data])
feature_anger = np.array([x['faceAttributes']['emotion']['anger'] for x in labels_data])
feature_contempt = np.array([x['faceAttributes']['emotion']['contempt'] for x in labels_data])
feature_disgust = np.array([x['faceAttributes']['emotion']['disgust'] for x in labels_data])
feature_fear = np.array([x['faceAttributes']['emotion']['fear'] for x in labels_data])
feature_happiness = np.array([x['faceAttributes']['emotion']['happiness'] for x in labels_data])
feature_neutral = np.array([x['faceAttributes']['emotion']['neutral'] for x in labels_data])
feature_sadness = np.array([x['faceAttributes']['emotion']['sadness'] for x in labels_data])
feature_surprise = np.array([x['faceAttributes']['emotion']['surprise'] for x in labels_data])

feature_moustache = np.array([x['faceAttributes']['facialHair']['moustache'] for x in labels_data])
feature_beard = np.array([x['faceAttributes']['facialHair']['beard'] for x in labels_data])
feature_sideburns = np.array([x['faceAttributes']['facialHair']['sideburns'] for x in labels_data])
feature_bald = np.array([x['faceAttributes']['hair']['bald'] for x in labels_data])
feature_invisible = np.array([x['faceAttributes']['hair']['invisible'] for x in labels_data])

num_example = len(qlatent_data)
feature_brownhair = np.zeros(num_example)
feature_grayhair = np.zeros(num_example)
feature_blondhair = np.zeros(num_example)
feature_blackhair = np.zeros(num_example)
feature_otherhair = np.zeros(num_example)
for i in range(num_example):
    tempt = labels_data[i]['faceAttributes']['hair']['hairColor']
    color_brown = [x['confidence']*int(x['color'] == 'brown') for x in tempt]
    color_gray = [x['confidence']*int(x['color'] == 'gray') for x in tempt]
    color_blond = [x['confidence']*int(x['color'] == 'blond') for x in tempt]
    color_black = [x['confidence']*int(x['color'] == 'black') for x in tempt]
    color_other = [x['confidence']*int(x['color'] == 'other') for x in tempt]
    if color_brown:
        feature_brownhair[i] = np.max(color_brown)
    if color_gray:
        feature_grayhair[i] = np.max(color_gray)
    if color_blond:
        feature_blondhair[i] = np.max(color_blond)
    if color_black:
        feature_blackhair[i] = np.max(color_black)
    if color_other:
        feature_otherhair[i] = np.max(color_other)

feature_array = np.zeros((num_example, 21), dtype = float)
feature_array[:,0] = feature_gender
feature_array[:,1] = feature_age
feature_array[:,2] = feature_smile
feature_array[:,3] = feature_anger
feature_array[:,4] = feature_contempt
feature_array[:,5] = feature_disgust
feature_array[:,6] = feature_fear
feature_array[:,7] = feature_happiness
feature_array[:,8] = feature_neutral
feature_array[:,9] = feature_sadness
feature_array[:,10] = feature_surprise
feature_array[:,11] = feature_moustache
feature_array[:,12] = feature_beard
feature_array[:,13] = feature_sideburns
feature_array[:,14] = feature_bald
feature_array[:,15] = feature_invisible
feature_array[:,16] = feature_brownhair
feature_array[:,17] = feature_grayhair
feature_array[:,18] = feature_blondhair
feature_array[:,19] = feature_blackhair
feature_array[:,20] = feature_otherhair

feature_array_nomalized = feature_array

np.save('dlatent_array.npy', dlatent_array)
np.save('dlatent_array_cut.npy', dlatent_array_cut)
np.save('feature_array.npy', feature_array)


In [ ]:
np.max(feature_array, axis = )  #21
np.min(feature_array, axis = )  #21
np.mean(feature_array, axis = )

1/(**-**) * (feature_array - **)

